#!/bin/bash -e

script_dir=$(dirname "$0")
source ${script_dir}/setup

HYDRA_HELM_VERSION=${HYDRA_HELM_VERSION:-v0.28.2}
HYDRA_VERSION=${HYDRA_VERSION:-v2.0.3}

exit_code=1
#helm status hydra &>/dev/null || exit_code=$?
if [[ $exit_code != 0 ]]; then
    echo "Setting up Postgres user and database"
    POSTGRES_DATABASES=hydra2 \
    POSTGRES_NAMESPACE=${HYDRA_NAMESPACE} \
    ${script_dir}/../postgres/bootstrap

    echo "Updating ory helm repository"
    helm repo add ory https://k8s.ory.sh/helm/charts 1>/dev/null
    helm repo update ory 1>/dev/null

    install_flags=""
    if [[ ${HYDRA_DEBUG} != false ]]; then
        install_flags="--debug"
    fi

    dsn="postgres://hydra2@postgres.${HYDRA_NAMESPACE}/hydra2?sslmode=disable"

    echo "Installing ory/hydra helm chart"
    helm upgrade --install hydra2 ory/hydra \
        ${install_flags} \
        --version "${HYDRA_HELM_VERSION}" \
        --create-namespace \
        --set "image.tag=${HYDRA_VERSION}" \
        --set "hydra.config.dsn=${dsn}" \
        --values "${script_dir}/hydra-values.yaml" \
        --wait
fi

kubectl apply -k ${script_dir}/${deployment_path}